
CREATE TABLE employees (
    emp_id INT,
    emp_name VARCHAR(50),
    age INT,
    salary INT,
    department VARCHAR(50),
    job_title VARCHAR(50),
    city VARCHAR(50),
    email VARCHAR(50)
);

INSERT INTO employees VALUES
(101, 'Rahul', 28, 50000, 'IT', 'Software Engineer', 'Delhi', 'rahul@company.com'),
(102, 'Priya', 32, 60000, 'HR', 'HR Manager', 'Mumbai', 'priya@company.com'),
(103, 'Aman', 25, 45000, 'IT', 'Junior Developer', 'Delhi', NULL),
(104, 'Neha', 35, 70000, 'Finance', 'Financial Analyst', 'Bangalore', 'neha@company.com'),
(105, 'Rohan', 29, 85000, 'IT', 'Software Engineer', 'Pune', 'rohan@company.com'),
(106, 'Simran', 27, 48000, 'HR', 'Recruiter', 'Delhi', 'simran@company.com'),
(107, 'Vishal', 31, 95000, 'IT', 'Senior Software Engineer', 'Mumbai', 'vishal@company.com'),
(108, 'Anaya', 26, 52000, 'IT', 'QA Engineer', 'Bangalore', NULL);

